-- AlterTable
ALTER TABLE "StudyBooking" DROP COLUMN "hasDrink",
ADD COLUMN     "drinkCount" INTEGER NOT NULL DEFAULT 0,
ALTER COLUMN "endTime" DROP NOT NULL,
ALTER COLUMN "hours" SET DEFAULT 0,
ALTER COLUMN "hours" SET DATA TYPE DECIMAL(6,2),
ALTER COLUMN "roomFee" SET DEFAULT 0;

-- AlterTable
ALTER TABLE "StudyConfig" DROP COLUMN "hourlyRate",
ADD COLUMN     "roomHourlyRate" DECIMAL(12,2) NOT NULL DEFAULT 0,
ADD COLUMN     "tableHourlyRate" DECIMAL(12,2) NOT NULL DEFAULT 0;

